cargo-features = ["edition"]

[package]
edition = '2018'
name = "dotter"
version = "0.1.0"
authors = ["Felipe Sere <felipesere@gmail.com>"]

[dependencies]
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
